version: "2"
services:
  server:
    build: ./server
    ports:
      - "8080:3005"
    depends_on:
      - auth
      - api
      - storage
    networks:
      - services_network
  auth:
    build: ./services/auth
    environment:
      - DB_HOST=mongo
    ports:
      - "6000:6000"
    depends_on:
      - mongo
    networks:
      - services_network
      - db_network
  messaging:
    build: ./services/messaging
    environment:
      - DB_HOST=mongo
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - services_network
      - db_network
  api:
    build: ./services/api
    environment:
      - DB_HOST=mongo
    ports:
      - "6001:6001"
    depends_on:
      - mongo 
    networks:
      - services_network
      - db_network
  notification:
    build: ./services/notification
    environment:
      - DB_HOST=mongo
    ports:
      - "6002:6002"
    depends_on:
      - mongo
    networks:
      - services_network
      - db_network
  storage:
    build: ./services/storage
    environment:
      - DB_HOST=mongo
    ports:
      - "6003:6003"
    depends_on:
      - mongo
    networks:
      - services_network
      - db_network
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    command: mongod --noauth --smallfiles
    volumes:
      - data-volume:/data/db
    networks:
      - db_network
volumes:
  data-volume:
networks:
  db_network:
    driver: bridge
  services_network:
    driver: bridge
